# Generated by Django 4.0.1 on 2022-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('infotxt', models.TextField()),
            ],
            options={
                'db_table': 'travel',
            },
        ),
    ]
