# Generated by Django 4.0.1 on 2022-01-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
    ]
